// AUTO-GENERATED by scripts/scan-playground-status.mjs. Do not edit by hand.
// Regenerated on every `pnpm dev` and `pnpm build` via the predev/prebuild hooks.
// Source: app/preview/_shared/integration-manifest.json + app/preview/_shared/lint-passes.json

export const INTEGRATED_IDS: ReadonlySet<string> = new Set([
  "app-chrome",
  "category-breakdown",
  "goal-list",
  "goal-progress",
  "goal-tracker",
  "investment-product",
  "onboarding",
  "pot-detail",
  "questionnaire-overlay",
  "spend-overview"
]);

export const CONFIRMED_IDS: ReadonlySet<string> = new Set([]);
